### ISSUE TITLE
Testing site performance

### ISSUE THREAD

**Issue by jcasman** [Oppkey/quarto-blog#100]
Use Chrome developer tools performance testing to measure bottlenecks of the web site. Using another measurement tool is fine.

Is it possible to compare with current R Consortium site? Which feels very slow. So the new site should presumably be noticeably faster.

**Comment by jcasman** [comment]
Per our discussion, using the Developer Tools Network tab and creating a spreadsheet is good. Please plan on measuring 6 pages. Add more if needed:

- homepage
- https://oppkeyquarto.netlify.app/members
- https://oppkeyquarto.netlify.app/all-projects/
- https://oppkeyquarto.netlify.app/webinars/webinars
- https://oppkeyquarto.netlify.app/blog/
- https://oppkeyquarto.netlify.app/posts/kolkata-r-user-group-a-rich-history-with-statistics/

**Comment by AirTechWick** [comment]
For the network dev tool tests I'm using these settings
Throttling: Wi-Fi (30 Mbs)

**Comment by AirTechWick** [comment]
https://docs.google.com/spreadsheets/d/1L-RPHWmJEs7C0Btasme5crYlxsXT5pwIHr7Yjmdin1c/edit?gid=0#gid=0

**Comment by jcasman** [comment]
Looks good!

Please add settings - Wi-Fi throttling
Please add Blog and specific blog example
Please add comparisons to original site pages

**Comment by AirTechWick** [comment]
https://vercel.com/blog/how-core-web-vitals-affect-seo
based on this article and official google documentation

The 3 main metrics that affect google search ranking are:
Largest Contentful Paint (LCP)
Interaction to Next Paint (INP)
Cumulative Layout Shift (CLS)
