### ISSUE TITLE
Build out homepage with R Consortium structure

### ISSUE THREAD

**Issue by jcasman** [Oppkey/quarto-blog#15]
## Build homepage with same structure as current site 

Current page here: https://www.r-consortium.org/

### Top thin bar: The Linux Foundation Projects
* Link to Linux Foundation info

### Main Header row: R Consortium logo, Main Nav bar, Social Media Links, Search
* Main Nam has Members, Projects, About, Webinars, R/Medicine, News, Code of Conduct
* Social Media Links has 4 icons linked to the R Consortium accounts: GitHub, YouTube, Mastodon, X.
   * Current site has just X, YouTube

### Main Image
* 1 Static Main Image
  * Current R Consortium site has a carousel

### What is R row
* Block of text, two links, embedded YouTube video

### Latest News and Updates
* Three columns of text and links to the newest blog posts
    * Expect that this needs to be updated manually. If there is a mechanism for listing the latest blog posts 
automatically, great. I expect we have text files in markdown for blog posts, and are not using a database.

### Joining R Consortium row
* Block of text and link

### Need Help? row
* Block of text and link

### Footer
* Block of text and links

## Same information in hand drawn sketch

![quarto-homepage](https://github.com/Oppkey/quarto-blog/assets/1075520/54557c37-74b8-4266-8846-d680c7a233ac)

**Comment by AirTechWick** [comment]
Looks like I can add custom CSS to the quarto blog which should help make it look close to the original
https://quarto.org/docs/output-formats/html-themes.html#theme-options

**Comment by jcasman** [comment]
@AirTechWick Do you think that's worth doing? Will it make the blog look better in your opinion? The current blog is marketing-focused: interviews, user groups, events, webinars. The new blog (which has no content and no current plan for content) is intended to be technical in scope. Having different styles for the blogs might really help differentiate them.

**Comment by AirTechWick** [comment]
If we're just doing the blog, then a different design but similar style should be good then. I wasn't sure how close to the original website you wanted but, I'll make sure it's a similar style then.

**Comment by jcasman** [comment]
Similar style is NOT a requirement.

**Comment by AirTechWick** [comment]
Okay, will work mainly on just adding the requirements then and not worry about similar style.

**Comment by jcasman** [comment]
Possible examples:

https://realworlddatascience.net/
https://nbdev.fast.ai/

both of these from the Websites section here: https://quarto.org/docs/gallery/

**Comment by jcasman** [comment]
> Okay, will work mainly on just adding the requirements then and not worry about similar style.

Yes, please focus on functionality first.
