### ISSUE TITLE
New Blog Post - Navigating R’s Impact in Vienna: Insights from the Finance and Pharmaceutical Sectors

### ISSUE THREAD

**Issue by PhatCa** [Oppkey/quarto-blog#153]

**Comment by PhatCa** [comment]
https://www.r-consortium.org/blog/2024/04/19/navigating-rs-impact-in-vienna-insights-from-the-finance-and-pharmaceutical-sectors

**Comment by jcasman** [comment]
The date is incorrect. Should be April 19, 2024. Currently it's May 19, 2024. Please fix.

https://www.r-consortium.org/blog/2024/04/19/navigating-rs-impact-in-vienna-insights-from-the-finance-and-pharmaceutical-sectors

**Comment by PhatCa** [comment]
date already changed and merged
