### ISSUE TITLE
Create Contributors Thank You page

### ISSUE THREAD

**Issue by jcasman** [Oppkey/quarto-blog#165]
Build a page with this information:

Contributors to this Website

The R language is open source and is supported worldwide by people who are enthusiastic to learn and improve. The R Consortium supports R infrastructure technology projects, events, webinars, R user groups, and much more. We support the R community and we benefit from it, too. 

The following people have helped contribute to this R Consortium quarto-based website:

- Simisani Ndaba, R-Ladies Gaborone chapter founder and organizer
- Isabella Velásquez, Sr. Product Marketing Manager, Posit
- Erik Rodriquez, San Jose State, Computer Science major
- Phat Ca, University of Hawaii, Computer Science major
- Priyanka Gagneja, R-Ladies Gaborone member

**Comment by AirTechWick** [comment]
Working on this

**Comment by AirTechWick** [comment]
Ill put it in `/about/thank-you` for now
![image](https://github.com/user-attachments/assets/8b8a150e-a2d5-4f18-912c-7e2ca326c3dc)
