### ISSUE TITLE
Another 5 blog posts from 2024

### ISSUE THREAD

**Issue by jcasman** [Oppkey/quarto-blog#173]
[Apply Now! R Consortium Infrastructure Steering Committee (ISC) Grant Program Open for Proposals!](https://www.r-consortium.org/blog/2024/03/01/apply-now-r-consortium-infrastructure-steering-committee-isc-grant-program-open-for-proposals)
[R Consortium](https://www.r-consortium.org/author/rcon) | [Announcement](https://www.r-consortium.org/category/announcement), [Blog](https://www.r-consortium.org/category/blog)
Help build R infrastructure! We're opening the call for proposals for the 2024 Infrastructure Steering Committee (ISC) Grant Program. The R Consortium is dedicated to enriching the R Ecosystem, directly…
[The R Consortium 2023: A Year of Growth and Innovation](https://www.r-consortium.org/blog/2024/02/28/the-r-consortium-2023-a-year-of-growth-and-innovation)
[R Consortium](https://www.r-consortium.org/author/rcon) | [Announcement](https://www.r-consortium.org/category/announcement), [Blog](https://www.r-consortium.org/category/blog)
Excerpted from the Annual Report Access the annual report here! Letter from the Chair — Mehar Pratap Singh, Chairman Welcome to the 2023 Annual Report of the R Consortium. This…
[Moffitt Cancer Center Bio-Data Club’s New Chapter in Spatial Data Analysis and Enhanced Hackathon Collaboration](https://www.r-consortium.org/blog/2024/02/27/moffitt-cancer-center-bio-data-clubs-new-chapter-in-spatial-data-analysis-and-enhanced-hackathon-collaboration)
[R Consortium](https://www.r-consortium.org/author/rcon) | [Blog](https://www.r-consortium.org/category/blog)
The R Consortium recently reconnected with Paul Stewart, founder of Moffitt Cancer Center Bio-Data Club in Tampa, Florida. Since the last update on January 6th, 2023, the Moffitt Cancer Center…
[Recap: R Validation Hub Community Meeting](https://www.r-consortium.org/blog/2024/02/23/recap-r-validation-hub-community-meeting)
[R Consortium](https://www.r-consortium.org/author/rcon) | [Blog](https://www.r-consortium.org/category/blog)
Join the R Validation Hub mailing list! The recent R Validation Hub Community meeting brought together around 50 participants to explore the concept of "validation" within the R programming ecosystem.…
[Join our R/Medicine Webinar: Quarto for Reproducible Medical Manuscripts](https://www.r-consortium.org/blog/2024/02/21/join-our-r-medicine-webinar-quarto-for-reproducible-medical-manuscripts)
[R Consortium](https://www.r-consortium.org/author/rcon) | [Blog](https://www.r-consortium.org/category/blog), [Events](https://www.r-consortium.org/category/events)
Join the R Consortium for an enlightening webinar on March 20th, 2024, at 4:00 PM ET, featuring Mine Cetinkaya-Rundel, Professor of the Practice of Statistical Science at Duke University. Discover…

**Comment by AirTechWick** [comment]
on it
