### ISSUE TITLE
Create Projects pages

### ISSUE THREAD

**Issue by jcasman** [Oppkey/quarto-blog#188]
This [Funded Projects page](https://oppkeyquarto.netlify.app/all-projects/funded-projects) links to 17 pages. Please recreate all remaining 12 pages. Checklist is below.

For each one, create an individual group page. Example for 2024 (group 1) is here: https://oppkeyquarto.netlify.app/all-projects/2024-group-1
* Note: Each group page includes a list of the projects at the top of the page and anchor links down to each project summary

Then on the Funded Projects page, switch links from going to the old original site to the new group page using anchor links.

Current status:

- [x] 2024 (group 1)
- [x] 2023 (group 2)
- [x] 2023 (group 1)
- [x] 2022 (group 2)
- [x] 2022 (group 1)
- [x] 2021 (group 2)
- [x] 2021 (group 1)
- [x] 2020 (group 2)
- [x] 2020 (group 1)
- [x] 2019 (group 2)
- [x] 2019 (group 1)
- [x] 2018 (group 2)
- [x] 2018 (group 1)
- [x] 2017 (group 2)
- [x] 2017 (group 1)
- [x] 2016 (group 2)
- [x] 2016 (group 1)

**Comment by AirTechWick** [comment]
on it

**Comment by jcasman** [comment]
Please continue with the other 15 pages. Please continue in reverse-chronological order. 2023, then 2022, then 2021, etc.

**Comment by jcasman** [comment]
Updated, 12 pages remaining.
