### ISSUE TITLE
Move Latest section up on homepage

### ISSUE THREAD

**Issue by jcasman** [Oppkey/quarto-blog#189]
I tried to do this, it did not immediately work.

On the original site, LATEST is right below WHAT IS R CONSORTIUM?

Currently, on the new site, it's the lowest section on the homepage. Move it up to the same position as the original site.

**Comment by AirTechWick** [comment]
This is an issue with Quarto, I remember in the first week or two trying but the only way possible is with the LATEST section at the very bottom due to quarto limitations.

**Comment by jcasman** [comment]
OK, I'm closing this issue
