### ISSUE TITLE
Add two new R plots to main carousel

### ISSUE THREAD

**Issue by jcasman** [Oppkey/quarto-blog#242]
First image, Survival Analysis
* Image already uploaded to Postimg here: https://i.postimg.cc/0NQNwKmH/survival-analysis2.png
* Text: R/Medicine Webinar: Visualizing Survival Data with the {ggsurvfit} R Package
   * Note, overlay text will be hard to see. Possibly align to bottom of image. Or create blue background behind white font
* Link: https://www.r-consortium.org/r-medicine-webinar-visualizing-survival-data-with-the-ggsurvfit-r-package
* Button text: Webinar Recording

Second image, Optimize Portfolios
* image on Postimg: https://i.postimg.cc/Wpxx6vVN/optimize-portfolios.png
* Text: Tidy Finance Webinar Series 
   * Note, overlay text will be hard to see. Possibly align to bottom of image. Or create blue background behind white font
* Link: https://www.r-consortium.org/tidy-finance-webinar-series
* Button text: Webinar Information

**Comment by AirTechWick** [comment]
Working on it
