### ISSUE TITLE
Document Workflow for New Blog Posts

### ISSUE THREAD

**Issue by codetricity** [Oppkey/quarto-blog#7]
Document workflow from the point where an outside contribute sends us an article in qmd format to the point where the blog appears on the new site.

There needs to be human authorization before the blog goes public.

The process is likely a branch and pull request.   Make note of any cautions regarding merge conflicts, thumbnail generation issues, or chart generation

**Comment by jcasman** [comment]
[Quarto Blog Workflow Documentation](https://docs.google.com/document/d/1O7WqVe8-ndXuwanzEz_jyoeB5Klj-e9wcJLlF2rqNmw/edit)
