### ISSUE TITLE
Using R to generate tables

### ISSUE THREAD

**Issue by jcasman** [Oppkey/quarto-blog#93]
Examine if it's possible to redo the table on this page using R: https://oppkeyquarto.netlify.app/about/join

R Consortium wants us to use the GT package.

I believe this site uses GT. Here's an example table: https://rconsortium.github.io/RMedicine_2024/Program.html

Here's their public repo: https://github.com/RConsortium/RMedicine_website

From ChatGPT:

The gt package in R allows users to create tables for data visualization and reporting. It offers a variety of table parts, including a header, stub, column labels, body, and footer, that can be combined to create tables that convey information. The gt package also supports formatting, styling, and theming tables, and can handle complex data structures. 

Here are some steps for using gt to create a table: 

Start with a data frame that contains the values to display. 

Use gt::gt() to turn the data frame into an editable table. 

Compose the table using the available elements and formatting. For example, users can change column names with gt::cols_label(), add titles with the tab header, or create joined columns called spanners with tab_spanner() layers. 

Render the table by printing it to the console, including it in an R Markdown document, or exporting it to a file using gtsave().

**Comment by AirTechWick** [comment]
Okay, working on it

**Comment by AirTechWick** [comment]
https://github.com/RConsortium/RMedicine_2024/blob/operations/Program.qmd
Table with gt

**Comment by jcasman** [comment]
Is there some visual editor available in RStudio or some way to edit the table that's reasonable?

**Comment by AirTechWick** [comment]
I don't see a way to generate gt tables within quarto only markdown or html tables
https://quarto.org/docs/visual-editor/content.html
